openapi: 3.0.0
info:
  title: Pet Store API
  version: 1.0.0
paths:
  /pets:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: The response for Pets post operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'

components:
  schemas:
    Pet:
      required:
        - petType
        - name
        - age
      properties:
        petType:
          type: string
        name:
          type: string
          description: The name of the pet
        age:
          type: integer
          minimum: 0
          description: Age of the pet in years
      discriminator:
        propertyName: petType
      oneOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'

    Cat:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          required:
            - whiskerLength
          properties:
            whiskerLength:
              type: integer
              minimum: 0
              description: Length of whiskers in centimeters

    Dog:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          required:
            - barkVolume
          properties:
            barkVolume:
              type: integer
              minimum: 0
              maximum: 100
              description: Volume of bark in decibels